media: src/images
content:
  - name: posts
    label: Posts
    type: collection
    path: src/posts
    fields: 
      - {name: title, label: Title, type: string }
      - {name: description, label: Description, type: string }
      - name: date 
        label: Date
        type: date
        options: 
          format: yyyy-MM_dd
      - {name: permalink, label: Permalink, type: string }
      - {name: body, label: Body, type: rich-text } 
  - name: pages
    label: About Page
    type: file
    path: src/about.md
    fields: 
      - {name: title, label: Title, type: string }
      - {name: layout, label: Layout, type: string }
      - {name: name, label: Name, type: string}
      - {name: image, label: Image, type: string}
      - {name: body, label: Body, type: rich-text }